### ISSUE TITLE
Invalid Cite2Urns able to be constructed

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/xcite#14]
`urn:cite2:hmt.vaimg.v1:test`

Not the period, not colon, after the `hmt` namespace. This constructs as a valid URN in 1.3 of xcite.

xcite thinks that `hmt.vaimg.v1` is the namespace.
It thinks that `vaimg` is the collection.

Fair enough… it is (my) bad data, but if this were a legit URN, it should have a final colon.

**Comment by neelsmith** [comment]
fixed and tested.  Will publish in next release.

**Comment by neelsmith** [comment]
Next release will be 2.3.1
