### ISSUE TITLE
Urgent: cite2urn.dropExtensions also drops versions!

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/xcite#15]
Reproduce in sbt console:

scala> val test = Cite2Urn("urn:cite2:hmt:vaimg.v1:VA012RN_0013@0.165,0.2755,0.335,0.022")
test: edu.holycross.shot.cite.Cite2Urn = urn:cite2:hmt:vaimg.v1:VA012RN_0013@0.165,0.2755,0.335,0.022

scala> test.dropExtensions
res19: edu.holycross.shot.cite.Cite2Urn = urn:cite2:hmt:vaimg:VA012RN_0013

**Comment by neelsmith** [comment]
easy typo of collection for collectionComponent.  Fixed in 2.3.1 release.
