### ISSUE TITLE
Method for reporting depth of citation hierarchy for a given URN

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/xcite#34]
`CtsUrn(urn:cts:greeekLit:tlg0012.tlg001.msA:1.1).citationDepth == 2`
 `CtsUrn(urn:cts:greeekLit:tlg0012.tlg001.msA.token:1.1.1).citationDepth == 3`

**Comment by neelsmith** [comment]
Duplicate of #2

Keeping this open as a sub-task on #2

**Comment by neelsmith** [comment]
This already exists:  its the `workLevel` function.  It returns an enumerated value you can case match on.

**Comment by neelsmith** [comment]
MIsread this.  Sorry:  reopening.

**Comment by Eumaeus** [comment]
Done. Tested.
